// Vault Core — Agent Action Generation Policy (Phase 9.1). PURE.
//
// Decides WHEN and HOW agents may auto-create Vault Actions from their existing
// internal signals (recommendations / memory / intelligence). The policy is the
// single safety throttle for generation:
//   • caps each agent to 1–2 actions per tick,
//   • requires a minimum Vera quality score + real evidence + reason + safe_preview,
//   • restricts AUTO-generated actions to INTERNAL targets only (internal/content/
//     report) — external targets are NEVER auto-generated by an agent (they remain
//     creatable only via other paths and always land adapter_disabled),
//   • leaves ALL approval/execution gating to the existing engine (this file never
//     approves, never executes, never mutates anything).
//
// No I/O, no DB, no external calls. Deterministic.

import { ACTION_META, INTERNAL_TARGETS } from "./policies";
import type { ActionType, TargetSystem, VaultActionInput } from "./types";

export const POLICY_VERSION = "9.1.0";

// Hard caps + thresholds (intentionally conservative to keep /actions low-noise).
export const MAX_ACTIONS_PER_AGENT = 2;
export const MIN_QUALITY_SCORE = 0.5;        // Vera quality floor for generation
export const MIN_EVIDENCE_ITEMS = 1;         // must cite at least one concrete signal
export const MISSION_VISIBLE_THRESHOLD = 0.6; // quality at/above which it headlines
// Dedupe lookback: an action sourced from the same signal within this window is a
// duplicate (prevents the same recommendation re-spawning an action every tick).
export const DEDUPE_WINDOW_HOURS = 72;

export interface AgentGenerationPolicy {
  /** The internal action_type an auto-generated action uses for this agent. */
  primaryActionType: ActionType;
  /** Action types this agent is ALLOWED to file (documents model permissibility). */
  allowedActionTypes: ActionType[];
  /** Target systems this agent may file against (external ones stay adapter_disabled). */
  allowedTargetSystems: TargetSystem[];
  /** Max auto-generated actions per tick for this agent (≤ MAX_ACTIONS_PER_AGENT). */
  maxPerTick: number;
}

// Per-agent generation config. The generator uses `primaryActionType` (always an
// INTERNAL target) so auto-generation can never produce an external-target action.
// `allowed*` lists document what each agent may file via any path, per the Phase 9.1
// spec — they are NOT a license for auto-generation to touch external systems.
export const AGENT_GENERATION_POLICY: Record<string, AgentGenerationPolicy> = {
  // Executive priority — internal review tasks from the daily/weekly brief.
  vanessa: {
    primaryActionType: "create_internal_task",
    allowedActionTypes: ["create_internal_task", "prepare_client_success_plan", "prepare_competitor_response", "prepare_tracking_fix", "prepare_budget_recommendation"],
    allowedTargetSystems: ["internal"],
    maxPerTick: 2,
  },
  // Client success — internal plans/check-ins. NEVER contacts clients directly;
  // client-facing drafts (email/sms) are L2 and remain adapter_disabled after approval.
  vivian: {
    primaryActionType: "prepare_client_success_plan",
    allowedActionTypes: ["prepare_client_success_plan", "create_internal_task", "draft_client_message"],
    allowedTargetSystems: ["internal", "content", "email", "sms"],
    maxPerTick: 2,
  },
  // Competitor / strategy — internal/content prep. No scraping, no live fetch.
  valentina: {
    primaryActionType: "prepare_competitor_response",
    allowedActionTypes: ["prepare_competitor_response", "prepare_content_idea", "prepare_budget_recommendation", "draft_meta_campaign"],
    allowedTargetSystems: ["internal", "content", "meta"],
    maxPerTick: 2,
  },
  // Marketing / campaign prep — internal review tasks + content/report drafts.
  veronica: {
    primaryActionType: "create_internal_task",
    allowedActionTypes: ["create_internal_task", "draft_report", "prepare_content_idea", "draft_lead_reply", "draft_client_message", "draft_meta_campaign"],
    allowedTargetSystems: ["internal", "content", "report", "meta", "email", "sms", "ghl"],
    maxPerTick: 2,
  },
  // Finance / revenue — internal review tasks. No Stripe mutation, no external invoices.
  valerie: {
    primaryActionType: "create_internal_task",
    allowedActionTypes: ["create_internal_task", "prepare_client_success_plan", "draft_report", "draft_invoice"],
    allowedTargetSystems: ["internal", "report", "stripe"],
    maxPerTick: 2,
  },
  // Analytics / performance — internal tracking/budget review prep.
  vega: {
    primaryActionType: "prepare_tracking_fix",
    allowedActionTypes: ["prepare_tracking_fix", "prepare_budget_recommendation", "create_internal_task", "draft_report"],
    allowedTargetSystems: ["internal", "report", "meta", "ghl"],
    maxPerTick: 2,
  },
};

export function getAgentGenerationPolicy(agentId: string): AgentGenerationPolicy | null {
  return AGENT_GENERATION_POLICY[agentId] ?? null;
}

export function isInternalTarget(target: TargetSystem): boolean {
  return INTERNAL_TARGETS.has(target);
}

export interface ShouldCreateInput {
  agentId: string;
  input: VaultActionInput;
  /** Vera quality score for the candidate (0..1). */
  qualityScore: number;
  /** Vera safety status — "unsafe" is always rejected. */
  safetyStatus: string;
  /** Evidence items the candidate cites. */
  evidenceCount: number;
}

export interface ShouldCreateDecision {
  ok: boolean;
  reason: string;
  /** Whether this action should headline Mission Control (vs. audit-only). */
  missionVisible: boolean;
}

/**
 * Gate a single generation candidate. Fails CLOSED — anything missing the required
 * shape, below quality, lacking evidence, flagged unsafe, or targeting an external
 * system is rejected. Returns the mission-visible flag for accepted candidates.
 */
export function shouldCreateAction(c: ShouldCreateInput): ShouldCreateDecision {
  const deny = (reason: string): ShouldCreateDecision => ({ ok: false, reason, missionVisible: false });

  const policy = getAgentGenerationPolicy(c.agentId);
  if (!policy) return deny(`no generation policy for agent "${c.agentId}"`);

  const { input } = c;
  if (!input.action_type) return deny("missing action_type");
  if (!policy.allowedActionTypes.includes(input.action_type)) {
    return deny(`action_type "${input.action_type}" not allowed for ${c.agentId}`);
  }

  const meta = ACTION_META[input.action_type];
  if (!meta) return deny(`unknown action_type "${input.action_type}"`);
  // Auto-generation is INTERNAL-ONLY. External targets are never auto-created.
  if (!isInternalTarget(meta.target)) return deny(`auto-generation may not target external system "${meta.target}"`);

  if (c.safetyStatus === "unsafe") return deny("Vera flagged unsafe wording");
  if (c.qualityScore < MIN_QUALITY_SCORE) return deny(`quality ${c.qualityScore.toFixed(2)} below floor ${MIN_QUALITY_SCORE}`);
  if (!input.title || input.title.trim().length < 8) return deny("missing or too-short title");
  if (!input.summary || input.summary.trim().length < 16) return deny("missing or too-short summary");
  if (!input.reason || input.reason.trim().length < 8) return deny("missing reason");
  if (c.evidenceCount < MIN_EVIDENCE_ITEMS) return deny("insufficient evidence");

  return {
    ok: true,
    reason: "accepted",
    missionVisible: c.qualityScore >= MISSION_VISIBLE_THRESHOLD,
  };
}
