// /api/victoria/prospects/[id]/briefing
// POST: Generate a pre-call briefing for a prospect
// Server-side only.

import { NextRequest, NextResponse } from "next/server";
import { generatePreCallBriefing } from "@/lib/victoria/agents/prospect-memory";
import { resolveServerRole } from "@/lib/auth/server-role";
import { can } from "@/lib/auth/permissions";

// ─────────────────────────────────────────────────────────────
// POST /api/victoria/prospects/:id/briefing
// Returns a full pre-call briefing generated by Claude Sonnet.
// Falls back to mock briefing when Anthropic is not configured.
// ─────────────────────────────────────────────────────────────

export async function POST(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const auth = await resolveServerRole();
  if (!auth) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  if (!can(auth.role, "canViewAiBuilder")) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }

  const { id } = await params;

  const result = await generatePreCallBriefing(id);

  if (!result) {
    return NextResponse.json(
      { error: "Prospect not found or no data available" },
      { status: 404 }
    );
  }

  return NextResponse.json({
    briefing: result.briefing,
    prospect: {
      id: result.prospect.id,
      name: result.prospect.name,
      company: result.prospect.company,
      vertical: result.prospect.vertical,
      deal_stage: result.prospect.deal_stage,
      urgency_level: result.prospect.urgency_level,
      total_calls: result.prospect.total_calls,
    },
  });
}
