// Vault Core — Creative Brief DRAFT templates (Phase 9.7; repositioned Vault-Co-internal-first).
//
// INTERNAL-FIRST (see ../operating-principles.ts): these are PLANS for VAULT CO's OWN content
// engine — founder-led content, Vault Co's own ad creative (to acquire roofing/home-service
// agency clients), market research, competitor response, JXN shoot briefs, and brand content.
// They are NOT client content deliverables. Every template is draft-only (nothing posted,
// published, uploaded, scheduled, or launched). Copy uses {{placeholder}} tokens where data
// is needed — never real data, never a live publish instruction. Instantiated into a
// VaultCreativeBriefInput, then re-validated/sanitized on save.

import { INTERNAL_FIRST_DEFAULTS } from "../operating-principles";
import type {
  BriefType, BriefPlatform, ContentFormat, VaultCreativeBriefInput,
} from "./types";

export interface CreativeTemplate {
  key: string;
  brief_type: BriefType;
  platform: BriefPlatform;
  content_format: ContentFormat;
  title: string;
  description: string;
  objective: string;
  audience: string;
  hook_bank: string[];
  script: string;
  shot_list: string[];
  editor_notes: string;
  visual_direction: string[];
  caption_options: string[];
  thumbnail_concepts: string[];
  deliverables: string[];
  missing_inputs: string[];
  compliance_notes: string[];
  evidence: string[];
  suggested_owner: string;
  notes: string;
}

// Vault Co's content targets its OWN prospects: home-service business OWNERS.
const OWNER_AUDIENCE =
  "Roofing & home-service business owners ($500k–$5M+) with inconsistent lead flow, missed calls, slow follow-up, no-shows, or poor lead quality.";

export const CREATIVE_TEMPLATES: CreativeTemplate[] = [
  {
    key: "vaultco_founder_led_reel", brief_type: "organic_reel", platform: "instagram", content_format: "reel",
    title: "Vault Co Founder-Led Reel",
    description: "Founder-to-camera organic reel building Vault Co authority with home-service owners.",
    objective: "Build Vault Co founder authority + trust with roofing/home-service owners (draft).",
    audience: OWNER_AUDIENCE,
    hook_bank: ["Most roofing marketing fails for ONE reason.", "I run the system that books jobs for home-service businesses — here's how.", "Stop buying shared leads. Do this instead."],
    script: "Hook (founder to camera) → the real problem (slow follow-up / missed calls) → the Vault Co system in one line → one sharp insight → soft CTA to learn more.",
    shot_list: ["Founder talking head (good audio)", "B-roll of the system/dashboard (no client data)", "Text-overlay key points"],
    editor_notes: "Captions on (sound-off). Tight cuts. Vault Co palette (premium/dark). 9:16. Never show real client data on screen.",
    visual_direction: ["Operator-to-operator tone", "Premium + dark brand look", "Confident, not hypey"],
    caption_options: ["The #1 reason roofing marketing fails (and the fix). ", "Booked jobs > 'leads.' Here's why."],
    thumbnail_concepts: ["Founder mid-sentence + bold insight text"],
    deliverables: ["1x 30–45s founder reel (9:16)"],
    missing_inputs: ["Founder footage", "Approved teaching angle"],
    compliance_notes: ["Keep claims accurate; no income/earnings guarantees."],
    evidence: ["Vault Co positioning doc", "Internal market research"],
    suggested_owner: "Veronica (production) + Vanessa (brand priority)",
    notes: "Authority layer; founder trust warms owners before the ask.",
  },
  {
    key: "vaultco_ai_growth_system_ad", brief_type: "video_ad_brief", platform: "meta", content_format: "video",
    title: "Vault Co AI Growth System Ad Brief",
    description: "Direct-response ad for Vault Co's ads + AI follow-up booked-appointment system.",
    objective: "Acquire roofing/home-service owners by selling the Vault Co growth system (draft).",
    audience: OWNER_AUDIENCE,
    hook_bank: ["Your leads are leaking — here's the plug.", "Ads alone don't book jobs. This does.", "What if every lead got a reply in 30 seconds?"],
    script: "0–3s: hook on the leaking-lead problem.\n3–12s: why ads alone fail (no follow-up/booking).\n12–22s: the Vault Co system — ads + AI follow-up + booking, human-approved.\n22–30s: proof framing + CTA to book a strategy call.",
    shot_list: ["Problem b-roll (missed call / ignored lead)", "System demo (follow-up replying, booking)", "Founder/operator credibility line"],
    editor_notes: "Captions on. Tight. Vault Co brand. 9:16 master + 1:1 cutdown. No raw client data.",
    visual_direction: ["Make the leaking-lead pain visceral", "Show the system working", "Trust markers"],
    caption_options: ["Stop losing jobs to slow follow-up. Book a Vault Co strategy call.", "Ads + AI follow-up = booked jobs."],
    thumbnail_concepts: ["Leaking-bucket metaphor + 'Stop Losing Jobs'"],
    deliverables: ["1x 30s ad (9:16)", "1x 1:1 cutdown", "3x hook variants for testing"],
    missing_inputs: ["System demo footage", "Proof points", "Target markets"],
    compliance_notes: ["Describe AI honestly (assists + human-approved); no overhyped or income-guarantee claims."],
    evidence: ["Speed-to-lead correlates with booking (internal)"],
    suggested_owner: "Veronica (ad creative) + Vega (speed-to-lead data)",
    notes: "Vault Co's sharpest acquisition angle.",
  },
  {
    key: "vaultco_owner_pain_point_reel", brief_type: "organic_reel", platform: "instagram", content_format: "reel",
    title: "Vault Co Roofing Owner Pain Point Reel",
    description: "Pain-point reel naming the exact frustrations of roofing owners.",
    objective: "Resonate with roofing owners' pain to drive saves/shares + inbound (draft).",
    audience: OWNER_AUDIENCE,
    hook_bank: ["3 things quietly killing your roofing revenue.", "If your phone rings and nobody answers fast, you're losing jobs.", "Your CRM is a graveyard of dead leads."],
    script: "Hook → name 2–3 specific owner pains (missed calls, slow follow-up, no-shows) → the fix in one line → soft CTA.",
    shot_list: ["Founder/talking head", "Pain-point text overlays", "Quick system glimpse"],
    editor_notes: "Snappy, relatable. Captions on. 9:16. On-screen pain-point numbers.",
    visual_direction: ["Empathetic + specific", "Operator credibility"],
    caption_options: ["Save this if your roofing calendar isn't full. ", "The hidden roofing revenue leaks. "],
    thumbnail_concepts: ["'3 Revenue Leaks' bold text"],
    deliverables: ["1x 30s reel (9:16)"],
    missing_inputs: ["Approved pain points from market research"],
    compliance_notes: ["Keep claims accurate; no income/earnings guarantees."],
    evidence: ["Internal market research", "Manual competitor intel"],
    suggested_owner: "Valentina (angles) + Veronica (production)",
    notes: "Series potential — batch 4–5 pain-point reels.",
  },
  {
    key: "vaultco_missed_call_recovery_ad", brief_type: "video_ad_brief", platform: "meta", content_format: "video",
    title: "Vault Co Missed Call Recovery Ad",
    description: "Ad built on the missed-call → lost-job pain and Vault Co's text-back recovery.",
    objective: "Acquire owners by dramatizing missed-call revenue loss + the Vault Co fix (draft).",
    audience: OWNER_AUDIENCE,
    hook_bank: ["Every missed call is a competitor's booked job.", "You missed 14 calls last week. That's real money.", "Miss the call, lose the job — unless you do this."],
    script: "Hook on missed-call loss → quantify it → show Vault Co's instant text-back + booking → CTA to a strategy call.",
    shot_list: ["Phone ringing / ignored", "Text-back replying instantly", "Calendar filling"],
    editor_notes: "Captions on. Punchy. 9:16 + 1:1. No raw client data.",
    visual_direction: ["Loss-aversion framing", "Show the recovery in action"],
    caption_options: ["Stop losing jobs to missed calls. ", "Every missed call = lost revenue. Fix it."],
    thumbnail_concepts: ["Missed-call screen + '$ Lost'"],
    deliverables: ["1x 30s ad (9:16)", "2x hook variants"],
    missing_inputs: ["Text-back demo footage", "Stat framing (no fabricated numbers)"],
    compliance_notes: ["No fabricated stats; no income/earnings guarantees."],
    evidence: ["Missed-call recovery is a core Vault Co lever"],
    suggested_owner: "Veronica (creative)",
    notes: "Loss aversion converts owners — keep numbers honest.",
  },
  {
    key: "vaultco_speed_to_lead_ad", brief_type: "ugc_ad_brief", platform: "meta", content_format: "ugc_video",
    title: "Vault Co Speed-to-Lead Ad Creative",
    description: "UGC-style ad on the speed-to-lead advantage for home-service owners.",
    objective: "Test UGC-style speed-to-lead hooks for cheaper Vault Co acquisition (draft).",
    audience: OWNER_AUDIENCE,
    hook_bank: ["POV: your business replies to every lead in 30 seconds.", "I used to lose leads to slow follow-up. Then this.", "Speed-to-lead is the cheat code for booked jobs."],
    script: "Creator/founder, handheld, natural light. Hook → relatable slow-follow-up problem → what Vault Co changed (instant reply + booking) → soft CTA.",
    shot_list: ["Selfie-style talking head", "Phone screen-record of instant reply (no PII)", "B-roll"],
    editor_notes: "Keep it raw + authentic. Auto-captions. Light branding until end. 9:16.",
    visual_direction: ["Unpolished + credible", "Natural audio"],
    caption_options: ["Speed-to-lead changed everything. ", "Reply in seconds, book more jobs."],
    thumbnail_concepts: ["Creator + '30-Second Reply' overlay"],
    deliverables: ["3x UGC hook variants (9:16)", "1x full UGC ad"],
    missing_inputs: ["Creator/founder footage (no creator PII stored here)", "Approved talking points"],
    compliance_notes: ["Truthful claims only; no fabricated testimonials or income guarantees."],
    evidence: ["UGC performs for trust-led B2B"],
    suggested_owner: "Veronica (with Vega hook performance notes)",
    notes: "Cheap to test; rotate hooks weekly.",
  },
  {
    key: "vaultco_case_study_creative", brief_type: "case_study", platform: "multi", content_format: "video",
    title: "Vault Co Case Study Creative Brief",
    description: "Results-driven Vault Co case study (no raw client data on screen).",
    objective: "Communicate a real Vault Co client result as a trust asset for acquisition (draft).",
    audience: "Roofing/home-service owners comparing agencies or skeptical of lead vendors.",
    hook_bank: ["How a roofer went from missed calls to a booked calendar with Vault Co."],
    script: "Situation → what Vault Co changed (system) → outcome (framed, no raw PII/numbers unless approved) → takeaway + CTA.",
    shot_list: ["Context b-roll", "Approved result framing graphics", "Optional client soundbite (permitted)"],
    editor_notes: "Frame results accurately; do NOT show raw dashboards/PII. Captions on. 9:16 + 16:9.",
    visual_direction: ["Credible + specific", "Brand-safe data framing"],
    caption_options: ["Real results, the honest way. ", "Proof over promises."],
    thumbnail_concepts: ["Result framing + client first name only"],
    deliverables: ["1x case-study short", "1x long-form cut"],
    missing_inputs: ["Approved metrics framing", "Client usage permission"],
    compliance_notes: ["No raw client data/PII on screen.", "Confirm usage permission + accuracy before any future use."],
    evidence: ["Case studies convert mid/bottom funnel"],
    suggested_owner: "Valerie (value framing) + Veronica (production)",
    notes: "Accuracy + permission first.",
  },
  {
    key: "vaultco_competitor_response_creative", brief_type: "competitor_response_creative", platform: "meta", content_format: "video",
    title: "Vault Co Competitor Response Creative",
    description: "Creative that differentiates Vault Co from lead vendors / typical agencies.",
    objective: "Differentiate Vault Co (vs. shared-lead vendors / generic agencies) for owners (draft).",
    audience: "Owners burned by shared-lead vendors or agencies that just 'run ads'.",
    hook_bank: ["Getting agency pitches? Read this first.", "Shared leads make you compete on price.", "'Ad management' isn't a growth system."],
    script: "Hook → name the usual failure (shared leads, slow follow-up, no system) → contrast with Vault Co's exclusive booked-appointment system → soft CTA. Never name/disparage a specific competitor.",
    shot_list: ["Founder talking head", "Contrast graphics (shared vs. exclusive)", "Proof b-roll"],
    editor_notes: "Confident, not negative. Never name competitors. Captions on. 9:16.",
    visual_direction: ["Differentiate on the model, not attacks", "Trust-forward"],
    caption_options: ["Before you hire an agency, check these 4 things. ", "Exclusive booked appointments > shared leads."],
    thumbnail_concepts: ["'Shared vs. Exclusive' split"],
    deliverables: ["1x 30s video (9:16)", "2x hook variants"],
    missing_inputs: ["Confirmed differentiators", "Internal competitor angle notes"],
    compliance_notes: ["Do not name, target, or disparage competitors.", "Keep comparative claims substantiated."],
    evidence: ["Internal Vault Core competitor intel (manual capture — no scraping)"],
    suggested_owner: "Valentina (angle) + Veronica (production)",
    notes: "Differentiate, never attack.",
  },
  {
    key: "vaultco_market_research_hook_bank", brief_type: "hook_bank", platform: "multi", content_format: "caption",
    title: "Vault Co Market Research Hook Bank",
    description: "Hooks derived from Vault Co market research + internal competitor intel.",
    objective: "Stock research-backed hooks targeting owner pains for Vault Co content (draft).",
    audience: OWNER_AUDIENCE,
    hook_bank: [
      "Most roofing leads die in the first 5 minutes.",
      "Your missed calls are someone else's booked jobs.",
      "Shared leads make you compete on price — exclusive appointments don't.",
      "Ads without follow-up is just expensive awareness.",
      "Your CRM is a graveyard of leads you already paid for.",
      "Speed-to-lead is the cheapest growth lever you're ignoring.",
    ],
    script: "(N/A — hook bank from market research. Each hook can seed a reel/ad brief.)",
    shot_list: ["(Per-hook in production.)"],
    editor_notes: "Tag each hook by owner pain + funnel stage for testing.",
    visual_direction: ["(Per-hook.)"],
    caption_options: ["(Hooks double as opening lines.)"],
    thumbnail_concepts: ["(Per-hook.)"],
    deliverables: ["6+ research-backed hooks"],
    missing_inputs: ["Latest market research notes", "Internal competitor intel"],
    compliance_notes: ["Hooks must not make unsubstantiated or income-guarantee claims."],
    evidence: ["Internal market research", "Manual competitor intel (no scraping)"],
    suggested_owner: "Valentina (research) + Veronica (creative)",
    notes: "Refresh from winners + new research monthly.",
  },
  {
    key: "vaultco_jxn_shoot_day", brief_type: "shoot_brief", platform: "internal", content_format: "video",
    title: "Vault Co JXN Shoot Day Brief",
    description: "Production brief for a JXN shoot day capturing Vault Co batch content.",
    objective: "Capture a batch of reusable Vault Co founder/ad/brand content in one shoot day (draft).",
    audience: "Internal production (JXN) — feeds Vault Co ads + organic.",
    hook_bank: ["(Capture multiple founder hook reads to test later.)"],
    script: "Run-of-show: founder hook reads, AI-system explainer, pain-point talking heads, brand b-roll, proof framing. Capture vertical + horizontal.",
    shot_list: ["Founder hook reads (x5)", "System/dashboard b-roll (no client data)", "Pain-point talking heads", "Brand b-roll", "Proof framing graphics setup"],
    editor_notes: "Log clips by setup. Flag best founder takes. Deliver organized raw + selects. Never capture real client data on screen.",
    visual_direction: ["Consistent Vault Co brand look", "Vertical-first", "Good audio (lav mics)"],
    caption_options: ["(N/A — capture day)"],
    thumbnail_concepts: ["(N/A — capture day)"],
    deliverables: ["Organized raw footage", "Selects reel", "5+ founder hook takes"],
    missing_inputs: ["Confirm shoot date with JXN", "Locations + brand assets", "Founder availability"],
    compliance_notes: ["No real client data/PII captured on screen."],
    evidence: ["Batch shooting maximizes Vault Co content ROI"],
    suggested_owner: "Veronica (production coordination)",
    notes: "One good shoot day fuels weeks of Vault Co content.",
  },
  {
    key: "vaultco_brand_story_reel", brief_type: "client_brand_story", platform: "instagram", content_format: "reel",
    title: "Vault Co Brand Story Reel",
    description: "Brand story reel communicating Vault Co's positioning + mission.",
    objective: "Communicate Vault Co's positioning + why it exists, to owners (draft).",
    audience: "Roofing/home-service owners evaluating marketing partners.",
    hook_bank: ["We don't do 'leads.' We build booked-appointment machines.", "Most agencies run ads. We run growth systems."],
    script: "Hook → the problem with typical agencies → the Vault Co system + operator philosophy → proof/positioning → soft CTA.",
    shot_list: ["Founder/brand talking head", "System b-roll (no client data)", "Results framing (no raw numbers/PII)"],
    editor_notes: "Premium, confident, on-brand (Vault gold/dark). Captions on. 9:16. Never show real client data.",
    visual_direction: ["Premium + dark", "Vault Co palette", "Confident tone"],
    caption_options: ["Roofing growth, systemized. — Vault Co"],
    thumbnail_concepts: ["Vault Co logo + bold positioning line"],
    deliverables: ["1x 30s brand reel (9:16)"],
    missing_inputs: ["Approved positioning lines", "Brand-safe b-roll (no client PII)"],
    compliance_notes: ["Never display real client data/PII on screen.", "Keep results framing accurate + non-misleading."],
    evidence: ["Vault Co positioning doc"],
    suggested_owner: "Vanessa (brand priority) + Veronica (production)",
    notes: "Brand layer; keep it premium.",
  },
  {
    key: "vaultco_content_calendar_pack", brief_type: "content_calendar", platform: "multi", content_format: "calendar",
    title: "Vault Co Content Calendar Pack",
    description: "A 2-week Vault Co organic content cadence plan (ideas only).",
    objective: "Plan a balanced 2-week Vault Co organic cadence targeting owners (draft).",
    audience: OWNER_AUDIENCE,
    hook_bank: ["(Per-idea hooks defined in each brief.)"],
    script: "Cadence plan (ideas only — each becomes its own brief): founder authority, owner pain-point, AI-system explainer, case-study/proof, competitor differentiation, brand.",
    shot_list: ["(Per-idea — see individual briefs.)"],
    editor_notes: "Balance authority/pain/proof/brand. Consistent Vault Co look. Each idea → its own brief.",
    visual_direction: ["Consistent grid aesthetic", "Mix of formats"],
    caption_options: ["(Per-idea captions defined later.)"],
    thumbnail_concepts: ["(Per-idea.)"],
    deliverables: ["Wk1: founder authority, owner pain-point, AI-system explainer", "Wk2: case study/proof, competitor differentiation, brand"],
    missing_inputs: ["Confirm cadence + capacity", "Source footage availability"],
    compliance_notes: ["Each produced item still requires its own human approval."],
    evidence: ["Consistency compounds organic reach"],
    suggested_owner: "Vanessa (priority) + Veronica (execution)",
    notes: "Ideas only; spin each into a brief.",
  },
  {
    key: "vaultco_thumbnail_concepts_pack", brief_type: "thumbnail_brief", platform: "youtube", content_format: "thumbnail",
    title: "Vault Co Thumbnail Concepts Pack",
    description: "Thumbnail concepts for a Vault Co video/short.",
    objective: "Increase click-through on Vault Co content with strong thumbnails (draft).",
    audience: "Home-service owners browsing growth/marketing content.",
    hook_bank: ["(Thumbnail text doubles as a hook.)"],
    script: "(N/A — visual concepts.)",
    shot_list: ["(Use selects from the related Vault Co video.)"],
    editor_notes: "High contrast, big readable text, expressive founder face or sharp metaphor. Test 3 concepts.",
    visual_direction: ["Bold text (<5 words)", "High contrast", "Vault Co brand"],
    caption_options: ["(N/A.)"],
    thumbnail_concepts: ["Founder + 'Stop Losing Jobs'", "Leaking bucket + '$ Lost'", "'Shared vs. Exclusive' split"],
    deliverables: ["3x thumbnail concepts"],
    missing_inputs: ["Source video selects", "Brand font/colors"],
    compliance_notes: ["No clickbait that misrepresents the content."],
    evidence: ["Thumbnails drive CTR on YouTube/Shorts"],
    suggested_owner: "Veronica",
    notes: "Always test at least 3.",
  },
  {
    key: "vaultco_hook_bank_pack", brief_type: "hook_bank", platform: "multi", content_format: "caption",
    title: "Vault Co Hook Bank Pack",
    description: "A general bank of reusable Vault Co acquisition hooks for testing.",
    objective: "Stock a tested-ready bank of Vault Co hooks across funnel stages (draft).",
    audience: OWNER_AUDIENCE,
    hook_bank: [
      "Ads alone don't book jobs. This does.",
      "Your leads are leaking — here's the plug.",
      "Reply in 30 seconds, book more jobs.",
      "Not shared leads. Exclusive booked appointments.",
      "The operator behind your growth, not another faceless agency.",
      "Booked jobs > 'leads.'",
    ],
    script: "(N/A — hook bank. Each hook can seed a reel/ad brief.)",
    shot_list: ["(Per-hook in production.)"],
    editor_notes: "Tag each hook by funnel stage + angle for testing.",
    visual_direction: ["(Per-hook.)"],
    caption_options: ["(Hooks double as opening captions.)"],
    thumbnail_concepts: ["(Per-hook.)"],
    deliverables: ["6+ tested-ready hooks"],
    missing_inputs: ["Performance data to prioritize (if available)"],
    compliance_notes: ["Hooks must not make unsubstantiated or income-guarantee claims."],
    evidence: ["Hook quality drives most of paid performance"],
    suggested_owner: "Veronica (Vega performance notes)",
    notes: "Refresh from winners monthly.",
  },
  {
    key: "vaultco_editor_brief", brief_type: "editor_brief", platform: "multi", content_format: "video",
    title: "Vault Co Editor Brief",
    description: "Editor brief to cut Vault Co raw footage into a polished short.",
    objective: "Turn Vault Co raw founder/proof footage into a polished short (draft).",
    audience: "Roofing/home-service owners (Vault Co prospects).",
    hook_bank: ["(Lead with the strongest founder soundbite.)"],
    script: "Open on the strongest soundbite → context → payoff/insight → Vault Co brand card. Keep under 40s.",
    shot_list: ["Use provided raw footage", "Insert system/brand b-roll (no client data)"],
    editor_notes: "Lead with the best soundbite. Captions on. Clean lower-thirds. Export 9:16 + 16:9. Remove any sensitive data.",
    visual_direction: ["Premium Vault Co look", "No over-production"],
    caption_options: ["(Pull from the script's key line.)"],
    thumbnail_concepts: ["Founder + key insight text"],
    deliverables: ["1x 9:16 short", "1x 16:9 cut"],
    missing_inputs: ["Raw footage", "Brand assets"],
    compliance_notes: ["Strip any sensitive/client data.", "Keep claims accurate."],
    evidence: ["Editing turns raw shoot days into shippable Vault Co content"],
    suggested_owner: "Veronica (coordinates editor)",
    notes: "Best soundbite first, always.",
  },
  {
    key: "vaultco_custom_creative_brief", brief_type: "custom", platform: "multi", content_format: "other",
    title: "Vault Co Custom Creative Brief",
    description: "Blank, structured starting point for a bespoke Vault Co creative brief.",
    objective: "Define the Vault Co creative objective (draft).",
    audience: OWNER_AUDIENCE,
    hook_bank: ["Draft hook 1", "Draft hook 2"],
    script: "Draft the script/outline here.",
    shot_list: ["Define shots"],
    editor_notes: "Define editor notes (format, captions, aspect ratios).",
    visual_direction: ["Define visual direction"],
    caption_options: ["Draft caption"],
    thumbnail_concepts: ["Draft thumbnail concept"],
    deliverables: ["Define deliverables"],
    missing_inputs: ["Objective", "Audience", "Source footage", "Brand assets"],
    compliance_notes: [],
    evidence: ["Add supporting evidence"],
    suggested_owner: "Veronica (creative)",
    notes: "Use when none of the presets fit. " + INTERNAL_FIRST_DEFAULTS.creativeBriefs,
  },
];

export function getCreativeTemplate(key: string): CreativeTemplate | undefined {
  return CREATIVE_TEMPLATES.find((t) => t.key === key);
}

export function creativeTemplateToInput(
  t: CreativeTemplate,
  opts: { client_id?: string | null; source_agent?: string | null } = {},
): VaultCreativeBriefInput {
  return {
    client_id: opts.client_id ?? null,
    title: t.title,
    description: t.description,
    brief_type: t.brief_type,
    source_agent: opts.source_agent ?? "veronica",
    platform: t.platform,
    content_format: t.content_format,
    objective: t.objective,
    audience: t.audience,
    hook_bank: t.hook_bank,
    script: t.script,
    shot_list: t.shot_list,
    editor_notes: t.editor_notes,
    visual_direction: t.visual_direction,
    caption_options: t.caption_options,
    thumbnail_concepts: t.thumbnail_concepts,
    deliverables: t.deliverables,
    missing_inputs: t.missing_inputs,
    compliance_notes: t.compliance_notes,
    evidence: [`Template: ${t.title}`, `Suggested owner: ${t.suggested_owner}`, t.notes, ...t.evidence],
    metadata: { template_key: t.key, suggested_owner: t.suggested_owner },
  };
}
