// Vault Core — Creative Brief DRAFT templates (Phase 9.7). PURE / static.
//
// Starter content/creative PLANS for common Vault Co roofing + brand moments. Every
// template is draft-only (nothing posted, published, uploaded, scheduled, or launched).
// Copy uses {{placeholder}} tokens where client data is needed — never real data, never a
// live publish instruction. Instantiated into a VaultCreativeBriefInput, then re-validated/
// sanitized on save.

import type {
  BriefType, BriefPlatform, ContentFormat, VaultCreativeBriefInput,
} from "./types";

export interface CreativeTemplate {
  key: string;
  brief_type: BriefType;
  platform: BriefPlatform;
  content_format: ContentFormat;
  title: string;
  description: string;
  objective: string;
  audience: string;
  hook_bank: string[];
  script: string;
  shot_list: string[];
  editor_notes: string;
  visual_direction: string[];
  caption_options: string[];
  thumbnail_concepts: string[];
  deliverables: string[];
  missing_inputs: string[];
  compliance_notes: string[];
  evidence: string[];
  suggested_owner: string;
  notes: string;
}

export const CREATIVE_TEMPLATES: CreativeTemplate[] = [
  {
    key: "roofing_video_ad", brief_type: "video_ad_brief", platform: "meta", content_format: "video",
    title: "Roofing Video Ad Brief",
    description: "Direct-response video ad concept for roof replacement/repair lead gen.",
    objective: "Drive qualified roofing leads via a Meta lead-form video ad (draft).",
    audience: "Homeowners 35–65 in {{service_area}} with aging or damaged roofs.",
    hook_bank: ["Your roof is failing — and you might not even know it.", "Don't wait for the next storm to find out your roof is shot.", "A new roof for less than you think."],
    script: "0–3s: Hook over a shot of a worn roof.\n3–10s: Problem — hidden damage costs more later.\n10–20s: Solution — {{business.name}}, licensed + insured, free estimate.\n20–30s: Proof — quick before/after + review.\nEnd card: 'Get your free estimate.'",
    shot_list: ["Drone/exterior of a worn roof", "Close-ups of damage (missing shingles, leaks)", "Crew working safely", "Before/after pair", "Owner-to-camera trust line"],
    editor_notes: "Captions on (sound-off viewing). Keep cuts tight (<2s). Brand colors + logo end card. 9:16 master + 1:1 cutdown.",
    visual_direction: ["Authentic, not stocky", "Real jobs with permission", "Trust markers visible (licensed/insured/warranty)"],
    caption_options: ["Free roof estimate — no pressure, just answers. 🏠", "Storm-ready? Find out with a free inspection."],
    thumbnail_concepts: ["Split before/after roof", "Bold text: 'Free Roof Estimate'"],
    deliverables: ["1x 30s video (9:16)", "1x 1:1 cutdown", "3x hook variants for testing"],
    missing_inputs: ["Real job footage/photos (with permission)", "Service area", "Warranty/financing details"],
    compliance_notes: ["Substantiate any warranty/financing claims before any future use."],
    evidence: ["Roofing buyer psychology playbook"],
    suggested_owner: "Veronica (ad creative)", notes: "Workhorse DR ad; test hooks first.",
  },
  {
    key: "roofing_ugc_hook", brief_type: "ugc_ad_brief", platform: "meta", content_format: "ugc_video",
    title: "Roofing UGC Hook Brief",
    description: "Creator/UGC-style ad with strong first-3-second hooks.",
    objective: "Test UGC-style hooks for cheaper, higher-trust roofing leads (draft).",
    audience: "Homeowners in {{service_area}}; skeptical of polished ads.",
    hook_bank: ["I almost paid $30k for a new roof… until I learned this.", "POV: your roofer actually tells you the truth.", "3 things every homeowner gets wrong about roof damage."],
    script: "Creator talks to camera, handheld, natural light. Hook → 1 relatable problem → what {{business.name}} did differently → soft CTA to a free estimate.",
    shot_list: ["Creator selfie-style talking head", "B-roll of their roof/home", "Optional screen-record of the estimate booking"],
    editor_notes: "Keep it raw. Auto-captions. No heavy branding until the end. 9:16.",
    visual_direction: ["Unpolished + authentic", "Natural audio", "Real homeowner energy"],
    caption_options: ["The roof talk no one gives you. 🏠", "Honest roofing > flashy roofing."],
    thumbnail_concepts: ["Creator mid-sentence with caption overlay"],
    deliverables: ["3x UGC hook variants (9:16)", "1x full UGC ad"],
    missing_inputs: ["Creator/UGC source (no creator PII stored here)", "Approved talking points"],
    compliance_notes: ["No fabricated testimonials; creator claims must be truthful."],
    evidence: ["UGC performs well for trust-led verticals"],
    suggested_owner: "Veronica (with Vega hook performance notes)", notes: "Cheap to test; rotate hooks weekly.",
  },
  {
    key: "storm_damage_reel", brief_type: "organic_reel", platform: "instagram", content_format: "reel",
    title: "Storm Damage Reel Brief",
    description: "Timely organic reel educating homeowners after a storm.",
    objective: "Build trust + inbound interest after storms in {{storm_affected_area}} (draft).",
    audience: "Local homeowners recently affected by storms.",
    hook_bank: ["After a storm, THIS is the first thing to check.", "Storm damage hides where you can't see it.", "Free storm inspection — here's why it matters."],
    script: "Hook → show subtle storm damage signs → 'get a free inspection' → reassurance (no pressure, honest assessment).",
    shot_list: ["Sky/storm b-roll", "Roof damage close-ups", "Inspector pointing out issues", "Talking head reassurance"],
    editor_notes: "Fast, informative, captions on. Trending-but-tasteful audio. 9:16.",
    visual_direction: ["Helpful, not fear-mongering", "Clear + factual"],
    caption_options: ["Storm just rolled through {{service_area}}? Here's your checklist. ⛈️"],
    thumbnail_concepts: ["Roof + storm sky with 'Storm Check' text"],
    deliverables: ["1x 20–30s reel (9:16)"],
    missing_inputs: ["Recent storm date/area", "Inspection availability"],
    compliance_notes: ["Do NOT guarantee insurance claim approval or outcomes.", "Follow local post-storm solicitation rules."],
    evidence: ["Timeliness drives storm-season engagement"],
    suggested_owner: "Veronica (with Valentina timing)", notes: "Ship fast in the storm window.",
  },
  {
    key: "roof_replacement_social_proof", brief_type: "organic_reel", platform: "instagram", content_format: "reel",
    title: "Roof Replacement Social Proof Brief",
    description: "Social-proof reel showcasing completed replacements + happy owners.",
    objective: "Build local credibility and warm inbound interest (draft).",
    audience: "Homeowners researching roofers in {{service_area}}.",
    hook_bank: ["Another {{service_area}} roof, done right.", "This is what 'licensed and insured' actually looks like."],
    script: "Montage of completed jobs → quick owner reaction → trust markers → soft CTA.",
    shot_list: ["Completed-roof beauty shots", "Owner reaction/handshake", "Crew + branded truck"],
    editor_notes: "Upbeat, proud, local. Captions on. 9:16.",
    visual_direction: ["Real completed jobs (with permission)", "Community pride"],
    caption_options: ["Proudly roofing {{service_area}}, one home at a time. 🏠"],
    thumbnail_concepts: ["Beautiful finished roof + 'Locally Trusted'"],
    deliverables: ["1x 20s reel (9:16)"],
    missing_inputs: ["Completed-job media + owner permission"],
    compliance_notes: ["Use real, permissioned footage/reviews only."],
    evidence: ["Social proof lifts trust pre-lead"],
    suggested_owner: "Veronica", notes: "Pairs well with ad retargeting.",
  },
  {
    key: "client_testimonial_edit", brief_type: "editor_brief", platform: "multi", content_format: "video",
    title: "Client Testimonial Edit Brief",
    description: "Editor brief to cut a raw testimonial into a polished short.",
    objective: "Turn a raw client testimonial into a trust-building short (draft).",
    audience: "Prospective clients evaluating {{business.name}}.",
    hook_bank: ["'I was nervous about the cost — then this happened.'"],
    script: "Open on the strongest soundbite → context → result → name/location card. Keep under 40s.",
    shot_list: ["Use provided raw interview", "Insert b-roll of the completed job"],
    editor_notes: "Lead with the best soundbite. Captions on. Clean lower-thirds. Export 9:16 + 16:9. Remove any sensitive personal details.",
    visual_direction: ["Warm, authentic", "No over-production"],
    caption_options: ["Real words from a real {{service_area}} homeowner."],
    thumbnail_concepts: ["Client smiling + quote text"],
    deliverables: ["1x 9:16 short", "1x 16:9 cut"],
    missing_inputs: ["Raw testimonial footage", "Written usage permission"],
    compliance_notes: ["Confirm written usage permission before any future publishing.", "Strip sensitive personal info."],
    evidence: ["Testimonials are top-converting trust assets"],
    suggested_owner: "Veronica (Vivian flags permission)", notes: "Permission first, always.",
  },
  {
    key: "before_after_reel", brief_type: "instagram_reel", platform: "instagram", content_format: "reel",
    title: "Before/After Transformation Reel",
    description: "Satisfying before/after roof transformation reel.",
    objective: "Drive saves/shares + warm interest via a transformation reel (draft).",
    audience: "Homeowners who value visible quality.",
    hook_bank: ["Wait for it… 👀", "From this… to THIS."],
    script: "Before shot → transition on beat → after reveal → quick trust line + soft CTA.",
    shot_list: ["Before (worn roof)", "Mid-progress", "After reveal (matched angle)"],
    editor_notes: "Beat-matched transition. Same camera angle before/after. Captions on. 9:16.",
    visual_direction: ["Satisfying reveal", "Matched framing"],
    caption_options: ["Swipe-stopping transformation in {{service_area}}. 🏠✨"],
    thumbnail_concepts: ["Split before/after"],
    deliverables: ["1x 15–20s reel (9:16)"],
    missing_inputs: ["Matched before/after footage"],
    compliance_notes: ["Use real, permissioned project media."],
    evidence: ["Transformations earn high saves/shares"],
    suggested_owner: "Veronica", notes: "Capture matched angles on every job.",
  },
  {
    key: "educational_roofing_reel", brief_type: "organic_reel", platform: "instagram", content_format: "reel",
    title: "Educational Roofing Reel",
    description: "Helpful, value-first reel that builds authority.",
    objective: "Build authority + trust with practical roofing tips (draft).",
    audience: "Homeowners researching roof care/repair.",
    hook_bank: ["3 signs your roof needs attention NOW.", "Roofers won't tell you this — but I will."],
    script: "Hook → 3 quick tips with visuals → 'when in doubt, get a free inspection.'",
    shot_list: ["Talking head", "Tip visuals/b-roll", "Optional whiteboard/graphics"],
    editor_notes: "Snappy, value-dense. Captions on. On-screen tip numbers. 9:16.",
    visual_direction: ["Authoritative + friendly", "Clear graphics"],
    caption_options: ["Save this before your next rainy day. ☔ #roofing"],
    thumbnail_concepts: ["'3 Roof Warning Signs' bold text"],
    deliverables: ["1x 30–45s reel (9:16)"],
    missing_inputs: ["Approved tips/claims"],
    compliance_notes: ["Tips must be accurate; avoid absolute guarantees."],
    evidence: ["Education builds durable authority"],
    suggested_owner: "Veronica (Vega angle notes)", notes: "Series potential — batch 4–5.",
  },
  {
    key: "jxn_shoot_day", brief_type: "shoot_brief", platform: "internal", content_format: "video",
    title: "JXN Shoot Day Brief",
    description: "Production brief for a JXN shoot day capturing batch content.",
    objective: "Capture a batch of reusable roofing + brand content in one shoot day (draft).",
    audience: "Internal production (JXN) — feeds ads + organic.",
    hook_bank: ["(Capture multiple hook reads to test later.)"],
    script: "Run-of-show: setups for ad hooks, testimonial, before/after, educational tips, brand b-roll. Capture vertical + horizontal.",
    shot_list: ["Talking-head hook reads (x5)", "Job-site b-roll", "Crew + truck branding", "Before/after pairs", "Owner testimonial (if available + permitted)"],
    editor_notes: "Log clips by setup. Flag best hook takes. Deliver organized raw + selects.",
    visual_direction: ["Consistent brand look", "Vertical-first", "Good audio (lav mics)"],
    caption_options: ["(N/A — capture day)"],
    thumbnail_concepts: ["(N/A — capture day)"],
    deliverables: ["Organized raw footage", "Selects reel", "5+ hook takes"],
    missing_inputs: ["Confirm shoot date with JXN", "Locations + permissions", "Talent/owner availability"],
    compliance_notes: ["Get on-site media permissions before capturing identifiable people/property."],
    evidence: ["Batch shooting maximizes content ROI"],
    suggested_owner: "Veronica (production coordination)", notes: "One good shoot day fuels weeks of content.",
  },
  {
    key: "vault_co_brand_reel", brief_type: "client_brand_story", platform: "instagram", content_format: "reel",
    title: "Vault Co Brand Reel",
    description: "Brand story reel for Vault Co (agency positioning).",
    objective: "Communicate Vault Co's positioning + results for roofers (draft).",
    audience: "Roofing business owners evaluating marketing partners.",
    hook_bank: ["We don't do 'leads.' We build roofing machines.", "Most agencies run ads. We run growth systems."],
    script: "Hook → the problem with typical agencies → the Vault Co system → proof/positioning → soft CTA to learn more.",
    shot_list: ["Founder/brand talking head", "System/dashboard b-roll (no client data)", "Results framing (no raw numbers/PII)"],
    editor_notes: "Premium, confident, on-brand (Vault gold/dark). Captions on. 9:16. Never show real client data on screen.",
    visual_direction: ["Premium + dark", "Vault Co brand palette", "Confident tone"],
    caption_options: ["Roofing growth, systemized. — Vault Co"],
    thumbnail_concepts: ["Vault Co logo + bold positioning line"],
    deliverables: ["1x 30s brand reel (9:16)"],
    missing_inputs: ["Approved positioning lines", "Brand-safe b-roll (no client PII)"],
    compliance_notes: ["Never display real client data/PII on screen.", "Keep results framing accurate + non-misleading."],
    evidence: ["Vault Co positioning doc"],
    suggested_owner: "Vanessa (brand priority) + Veronica (production)", notes: "Brand layer; keep it premium.",
  },
  {
    key: "competitor_response_creative", brief_type: "competitor_response_creative", platform: "meta", content_format: "video",
    title: "Competitor Response Creative",
    description: "Creative angle that differentiates without naming competitors.",
    objective: "Win comparison-shopping homeowners by differentiating on trust/quality (draft).",
    audience: "Homeowners comparing roofers in {{service_area}}.",
    hook_bank: ["Getting roofing quotes? Read this first.", "Cheapest roof quote ≠ best roof."],
    script: "Hook → common pitfall when comparing roofers → what to look for (licensed/insured/warranty/reviews) → why {{business.name}} fits → soft CTA.",
    shot_list: ["Talking head", "Checklist graphics", "Proof b-roll"],
    editor_notes: "Confident, not negative. Never name/disparage competitors. Captions on. 9:16.",
    visual_direction: ["Differentiate on value, not attacks", "Trust-forward"],
    caption_options: ["Before you pick a roofer, check these 4 things. ✅"],
    thumbnail_concepts: ["'4 Things to Check' checklist"],
    deliverables: ["1x 30s video (9:16)", "2x hook variants"],
    missing_inputs: ["Confirmed differentiators vs. market", "Internal competitor angle notes"],
    compliance_notes: ["Do not name, target, or disparage the competitor.", "Keep comparative claims substantiated."],
    evidence: ["Internal competitor intel (manual capture — no scraping)"],
    suggested_owner: "Valentina (angle) + Veronica (production)", notes: "Differentiate, never attack.",
  },
  {
    key: "content_calendar_pack", brief_type: "content_calendar", platform: "multi", content_format: "calendar",
    title: "Content Calendar Pack",
    description: "A 2-week organic content cadence plan (ideas only).",
    objective: "Plan a balanced 2-week organic content cadence (draft).",
    audience: "Local homeowners + brand followers.",
    hook_bank: ["(Per-idea hooks defined in each brief.)"],
    script: "Cadence plan (ideas only — each becomes its own brief): educational, social proof, before/after, testimonial, storm/seasonal, brand.",
    shot_list: ["(Per-idea — see individual briefs.)"],
    editor_notes: "Balance value/proof/brand. Keep a consistent look. Each idea → its own brief for production.",
    visual_direction: ["Consistent grid aesthetic", "Mix of formats"],
    caption_options: ["(Per-idea captions defined later.)"],
    thumbnail_concepts: ["(Per-idea.)"],
    deliverables: ["Wk1: educational, social proof, before/after", "Wk2: testimonial, seasonal/storm, brand"],
    missing_inputs: ["Confirm cadence + capacity", "Source media availability"],
    compliance_notes: ["Each produced item still requires its own human approval."],
    evidence: ["Consistency compounds organic reach"],
    suggested_owner: "Vanessa (priority) + Veronica (execution)", notes: "Ideas only; spin each into a brief.",
  },
  {
    key: "thumbnail_concepts_pack", brief_type: "thumbnail_brief", platform: "youtube", content_format: "thumbnail",
    title: "Thumbnail Concepts Pack",
    description: "Thumbnail concepts for a roofing video/short.",
    objective: "Increase click-through with strong thumbnail concepts (draft).",
    audience: "Homeowners browsing roofing content.",
    hook_bank: ["(Thumbnail text doubles as a hook.)"],
    script: "(N/A — visual concepts.)",
    shot_list: ["(Use selects from the related video.)"],
    editor_notes: "High contrast, big readable text, expressive face or striking before/after. Test 3 concepts.",
    visual_direction: ["Bold text (<5 words)", "High contrast", "Clear focal point"],
    caption_options: ["(N/A.)"],
    thumbnail_concepts: ["Before/after split + 'WOW'", "Shocked homeowner + 'My roof did WHAT?'", "Bold '$ Saved' + new roof"],
    deliverables: ["3x thumbnail concepts"],
    missing_inputs: ["Source video selects", "Brand font/colors"],
    compliance_notes: ["No clickbait that misrepresents the content."],
    evidence: ["Thumbnails drive CTR on YouTube/Shorts"],
    suggested_owner: "Veronica", notes: "Always test at least 3.",
  },
  {
    key: "hook_bank_pack", brief_type: "hook_bank", platform: "multi", content_format: "caption",
    title: "Hook Bank Pack",
    description: "A bank of reusable roofing hooks for testing.",
    objective: "Stock a tested-ready bank of roofing hooks (draft).",
    audience: "Homeowners across funnel stages.",
    hook_bank: [
      "Your roof is lying to you.",
      "I almost overpaid for a roof — here's what saved me.",
      "3 signs your roof won't survive the next storm.",
      "The truth about 'free' roof inspections.",
      "What roofers don't want you to know.",
      "Cheapest quote ≠ best roof.",
    ],
    script: "(N/A — hook bank. Each hook can seed a reel/ad brief.)",
    shot_list: ["(Per-hook in production.)"],
    editor_notes: "Tag each hook by funnel stage + angle for testing.",
    visual_direction: ["(Per-hook.)"],
    caption_options: ["(Hooks double as opening captions.)"],
    thumbnail_concepts: ["(Per-hook.)"],
    deliverables: ["6+ tested-ready hooks"],
    missing_inputs: ["Performance data to prioritize (if available)"],
    compliance_notes: ["Hooks must not make unsubstantiated guarantees."],
    evidence: ["Hook quality drives most of paid performance"],
    suggested_owner: "Veronica (Vega performance notes)", notes: "Refresh from winners monthly.",
  },
  {
    key: "case_study_creative", brief_type: "case_study", platform: "multi", content_format: "video",
    title: "Case Study Creative Brief",
    description: "Results-driven case-study creative (no raw client data on screen).",
    objective: "Communicate a real client result as a trust asset (draft).",
    audience: "Prospective clients + roofing owners.",
    hook_bank: ["How {{client_first_name}} booked more roofing jobs in {{timeframe}}."],
    script: "Situation → what we changed → outcome (framed, no raw PII/numbers unless approved) → takeaway.",
    shot_list: ["Context b-roll", "Approved result framing graphics", "Optional client soundbite (permitted)"],
    editor_notes: "Frame results accurately; do NOT show raw dashboards/PII. Captions on. 9:16 + 16:9.",
    visual_direction: ["Credible + specific", "Brand-safe data framing"],
    caption_options: ["Real results, the honest way."],
    thumbnail_concepts: ["Result framing + client first name only"],
    deliverables: ["1x case-study short", "1x long-form cut"],
    missing_inputs: ["Approved metrics framing", "Client usage permission"],
    compliance_notes: ["No raw client data/PII on screen.", "Confirm usage permission + accuracy before any future publishing."],
    evidence: ["Case studies convert mid/bottom funnel"],
    suggested_owner: "Valerie (value framing) + Veronica (production)", notes: "Accuracy + permission first.",
  },
  {
    key: "custom_creative_brief", brief_type: "custom", platform: "multi", content_format: "other",
    title: "Custom Creative Brief",
    description: "Blank, structured starting point for a bespoke creative brief.",
    objective: "Define the creative objective (draft).",
    audience: "Define the target audience.",
    hook_bank: ["Draft hook 1", "Draft hook 2"],
    script: "Draft the script/outline here.",
    shot_list: ["Define shots"],
    editor_notes: "Define editor notes (format, captions, aspect ratios).",
    visual_direction: ["Define visual direction"],
    caption_options: ["Draft caption"],
    thumbnail_concepts: ["Draft thumbnail concept"],
    deliverables: ["Define deliverables"],
    missing_inputs: ["Objective", "Audience", "Source media", "Brand assets"],
    compliance_notes: [],
    evidence: ["Add supporting evidence"],
    suggested_owner: "Veronica (creative)", notes: "Use when none of the presets fit; fill in before review.",
  },
];

export function getCreativeTemplate(key: string): CreativeTemplate | undefined {
  return CREATIVE_TEMPLATES.find((t) => t.key === key);
}

export function creativeTemplateToInput(
  t: CreativeTemplate,
  opts: { client_id?: string | null; source_agent?: string | null } = {},
): VaultCreativeBriefInput {
  return {
    client_id: opts.client_id ?? null,
    title: t.title,
    description: t.description,
    brief_type: t.brief_type,
    source_agent: opts.source_agent ?? "veronica",
    platform: t.platform,
    content_format: t.content_format,
    objective: t.objective,
    audience: t.audience,
    hook_bank: t.hook_bank,
    script: t.script,
    shot_list: t.shot_list,
    editor_notes: t.editor_notes,
    visual_direction: t.visual_direction,
    caption_options: t.caption_options,
    thumbnail_concepts: t.thumbnail_concepts,
    deliverables: t.deliverables,
    missing_inputs: t.missing_inputs,
    compliance_notes: t.compliance_notes,
    evidence: [`Template: ${t.title}`, `Suggested owner: ${t.suggested_owner}`, t.notes, ...t.evidence],
    metadata: { template_key: t.key, suggested_owner: t.suggested_owner },
  };
}
