// Vault Core — Client Health / Retention Risk DRAFT templates (Phase 9.8). PURE / static.
//
// Starter internal client-success PLANS for common Vault Co retention moments. Every
// template is draft-only (no client outreach, no SMS/email, no GHL/CRM change, no workflow
// run, no money movement). Scores/labels are advisory TEXT only; client-specific values
// use {{placeholder}} tokens — never real provider IDs, raw PII, or payloads. Instantiated
// into a VaultClientHealthDraftInput, then re-validated/sanitized on save.

import type { HealthType, VaultClientHealthDraftInput } from "./types";

export interface ClientHealthTemplate {
  key: string;
  health_type: HealthType;
  title: string;
  description: string;
  health_score: string;
  risk_level_label: string;
  risk_reasons: string[];
  missing_access: string[];
  missing_assets: string[];
  delivery_risks: string[];
  communication_risks: string[];
  next_best_actions: string[];
  owner_notes: string;
  save_plan: string[];
  upsell_opportunities: string[];
  missing_inputs: string[];
  compliance_notes: string[];
  evidence: string[];
  suggested_owner: string;
  notes: string;
}

export const CLIENT_HEALTH_TEMPLATES: ClientHealthTemplate[] = [
  {
    key: "client_health_review",
    health_type: "client_health_review",
    title: "Vault Co Client Health Review",
    description: "Full internal health read on a Vault Co client: delivery, results, responsiveness, payment, and relationship signals in one review.",
    health_score: "{{score}}/100",
    risk_level_label: "{{risk_label}}",
    risk_reasons: ["Summarize the top 3 signals driving the score (results, responsiveness, payment, delivery)"],
    missing_access: ["List any platform access still outstanding"],
    missing_assets: ["List any creative/brand assets still outstanding"],
    delivery_risks: ["Note anything blocking fulfillment this period"],
    communication_risks: ["Note response cadence and last-touch recency"],
    next_best_actions: ["Prepare the single highest-leverage internal step for this client"],
    owner_notes: "Handoff context for Nick/Jaxon: what changed since the last review and what to watch.",
    save_plan: [],
    upsell_opportunities: ["Note any expansion signal worth validating later"],
    missing_inputs: ["Confirm score inputs", "Confirm period reviewed"],
    compliance_notes: [],
    evidence: ["Internal delivery + responsiveness signals (Vivian)", "Performance context (Vega)"],
    suggested_owner: "Vivian (Client Success Operator)",
    notes: "The baseline health artifact; run per client per period.",
  },
  {
    key: "retention_risk_review",
    health_type: "retention_risk_review",
    title: "Vault Co Retention Risk Review",
    description: "Internal review of a client showing churn signals — what is driving risk and what Vault Co should prepare internally.",
    health_score: "{{score}}/100",
    risk_level_label: "At risk",
    risk_reasons: ["Identify the churn drivers (results gap, responsiveness drop, payment friction, expectation mismatch)"],
    missing_access: [],
    missing_assets: [],
    delivery_risks: ["Note any delivery gap feeding the risk"],
    communication_risks: ["Note response pattern changes (slower replies, shorter answers, missed meetings)"],
    next_best_actions: ["Prepare an internal save assessment before any human outreach decision"],
    owner_notes: "Why this client is flagged now, and the decision Nick/Jaxon need to make.",
    save_plan: ["Diagnose the root cause with evidence", "Define what 'saved' looks like for this client", "Prepare a human-led conversation plan (a human decides and acts)"],
    upsell_opportunities: [],
    missing_inputs: ["Confirm churn signals with evidence", "Confirm renewal/contract timing"],
    compliance_notes: [],
    evidence: ["Responsiveness trend (Vivian)", "Results trend (Vega)", "Payment context (Valerie)"],
    suggested_owner: "Vivian (Vanessa escalates high-risk internally)",
    notes: "Flag early; the save plan is human-led — nothing here acts on the client.",
  },
  {
    key: "missing_access_review",
    health_type: "missing_access_review",
    title: "Vault Co Missing Access Review",
    description: "Internal warning list of platform access Vault Co still needs from a client to deliver (ad account, page, domain, tracking, billing portal).",
    health_score: "{{score}}/100",
    risk_level_label: "Blocked",
    risk_reasons: ["Access gaps are blocking or degrading delivery"],
    missing_access: ["Meta Business Manager / ad account permission", "Page / Instagram permission", "Tracking / pixel / domain access", "{{other_access}}"],
    missing_assets: [],
    delivery_risks: ["Which deliverables are blocked by each access gap"],
    communication_risks: [],
    next_best_actions: ["Prepare an onboarding-access request message draft for human review (see /message-drafts)"],
    owner_notes: "Which access item unblocks the most delivery, and who on the client side owns it.",
    save_plan: [],
    upsell_opportunities: [],
    missing_inputs: ["Confirm exact access items outstanding", "Confirm client-side owner"],
    compliance_notes: [],
    evidence: ["Onboarding checklist state", "Delivery blockers (Vivian)"],
    suggested_owner: "Vivian (pairs with an onboarding_access_request message draft)",
    notes: "Pairs with the message-draft lane; this artifact never reaches the client.",
  },
  {
    key: "missing_assets_review",
    health_type: "missing_assets_review",
    title: "Vault Co Missing Asset Review",
    description: "Internal warning list of creative/brand assets Vault Co still needs from a client (logos, photos, testimonials, offers, brand guidelines).",
    health_score: "{{score}}/100",
    risk_level_label: "Watch",
    risk_reasons: ["Asset gaps are limiting creative quality or volume"],
    missing_access: [],
    missing_assets: ["Logo / brand files", "Job-site photos or before/afters", "Testimonials / reviews", "{{other_assets}}"],
    delivery_risks: ["Which creatives/campaigns are degraded by each missing asset"],
    communication_risks: [],
    next_best_actions: ["Prepare an asset-request checklist for the next human-led client touchpoint"],
    owner_notes: "Rank assets by creative impact so the team asks for the right things first.",
    save_plan: [],
    upsell_opportunities: [],
    missing_inputs: ["Confirm asset list against the creative brief needs"],
    compliance_notes: [],
    evidence: ["Creative brief requirements", "Creative library gaps"],
    suggested_owner: "Vivian (with Veronica creative context)",
    notes: "Keep tied to actual creative-brief needs, not a generic wishlist.",
  },
  {
    key: "stalled_delivery_review",
    health_type: "stalled_delivery_review",
    title: "Vault Co Stalled Delivery Review",
    description: "Internal review of a deliverable that has stalled — what stalled, why, and the internal unblock plan.",
    health_score: "{{score}}/100",
    risk_level_label: "At risk",
    risk_reasons: ["Deliverable {{deliverable}} has been stalled for {{days_stalled}} days"],
    missing_access: ["Any access gap contributing to the stall"],
    missing_assets: ["Any asset gap contributing to the stall"],
    delivery_risks: ["Knock-on effects if the stall continues (results, trust, renewal)"],
    communication_risks: ["Whether the client has noticed / asked about it"],
    next_best_actions: ["Assign an internal owner and an unblock step with a date"],
    owner_notes: "Be precise about the single blocking cause — access, asset, decision, or internal bandwidth.",
    save_plan: [],
    upsell_opportunities: [],
    missing_inputs: ["Confirm what is actually blocking", "Confirm internal owner"],
    compliance_notes: [],
    evidence: ["Delivery timeline (Vivian)", "Operator queue state"],
    suggested_owner: "Vivian (Vanessa prioritizes if client-visible)",
    notes: "A stall the client can see is a retention risk; treat it with that weight.",
  },
  {
    key: "communication_risk_review",
    health_type: "communication_risk_review",
    title: "Vault Co Communication Risk Review",
    description: "Internal read on a client going quiet or cooling — response pattern, last touches, and what Vault Co should prepare.",
    health_score: "{{score}}/100",
    risk_level_label: "Cooling",
    risk_reasons: ["Response gap of {{days_quiet}} days against a baseline of {{baseline}}"],
    missing_access: [],
    missing_assets: [],
    delivery_risks: [],
    communication_risks: ["No reply to the last {{unanswered_count}} touchpoints", "Meeting attendance pattern"],
    next_best_actions: ["Prepare a check-in message draft for human review (see /message-drafts)"],
    owner_notes: "Distinguish 'busy season' quiet from 'disengaging' quiet — use the evidence, not vibes.",
    save_plan: [],
    upsell_opportunities: [],
    missing_inputs: ["Confirm last-touch dates", "Confirm baseline response cadence"],
    compliance_notes: [],
    evidence: ["Touchpoint history (internal)", "Meeting attendance (internal)"],
    suggested_owner: "Vivian (pairs with a client_check_in message draft)",
    notes: "An internal read on responsiveness — never a judgment shared with the client.",
  },
  {
    key: "onboarding_risk_review",
    health_type: "onboarding_risk_review",
    title: "Vault Co Onboarding Risk Review",
    description: "Internal review of a new client whose onboarding is dragging — friction points and the internal plan to get to first value fast.",
    health_score: "{{score}}/100",
    risk_level_label: "Watch",
    risk_reasons: ["Onboarding day {{day_count}} without {{milestone}} reached"],
    missing_access: ["Access items still outstanding from onboarding"],
    missing_assets: ["Assets still outstanding from onboarding"],
    delivery_risks: ["First-campaign / first-value timeline slipping"],
    communication_risks: ["Client momentum cooling before first value lands"],
    next_best_actions: ["Compress the path to first value: pick the one milestone that proves momentum"],
    owner_notes: "New clients churn on slow starts; time-to-first-value is the number that matters.",
    save_plan: [],
    upsell_opportunities: [],
    missing_inputs: ["Confirm onboarding checklist state", "Confirm first-value milestone"],
    compliance_notes: [],
    evidence: ["Onboarding checklist (Vivian)", "Kickoff notes"],
    suggested_owner: "Vivian (Client Success Operator)",
    notes: "Run automatically in spirit at day 7/14/21 of any onboarding (human-created for now).",
  },
  {
    key: "fulfillment_bottleneck_review",
    health_type: "fulfillment_bottleneck_review",
    title: "Vault Co Fulfillment Bottleneck Review",
    description: "Internal summary of a recurring fulfillment bottleneck across clients — where delivery slows down and what fixes it.",
    health_score: "{{score}}/100",
    risk_level_label: "Operational",
    risk_reasons: ["Bottleneck: {{bottleneck}} affecting {{client_count}} clients"],
    missing_access: [],
    missing_assets: [],
    delivery_risks: ["Throughput / quality impact while the bottleneck persists"],
    communication_risks: [],
    next_best_actions: ["Propose the system/process fix (may become a System Proposal)"],
    owner_notes: "If this recurs across clients it is a Vault Co system gap, not a client problem.",
    save_plan: [],
    upsell_opportunities: [],
    missing_inputs: ["Confirm affected clients", "Confirm root cause"],
    compliance_notes: [],
    evidence: ["Delivery timelines across clients", "Operator queue patterns"],
    suggested_owner: "Vivian (with Vanessa for prioritization)",
    notes: "Feeds the System Creation engine when the fix is structural.",
  },
  {
    key: "client_save_plan",
    health_type: "client_save_plan",
    title: "Vault Co Client Save Plan",
    description: "Internal save plan for a client at real risk of leaving — diagnosis, save definition, and a human-led conversation plan.",
    health_score: "{{score}}/100",
    risk_level_label: "Critical",
    risk_reasons: ["Primary churn driver: {{churn_driver}}", "Secondary signals: {{secondary_signals}}"],
    missing_access: [],
    missing_assets: [],
    delivery_risks: ["What must visibly improve for the client to feel the save"],
    communication_risks: ["Current relationship temperature"],
    next_best_actions: ["Nick/Jaxon decide the save conversation timing and owner (human-led)"],
    owner_notes: "The save is a human conversation backed by a delivery fix — this plan preps both.",
    save_plan: [
      "Diagnose: confirm the root cause with evidence, not assumption",
      "Fix: the delivery change Vault Co commits to internally",
      "Frame: the human-led conversation outline (a human decides and speaks)",
      "Prove: the measurable result that demonstrates the fix within 30 days",
    ],
    upsell_opportunities: [],
    missing_inputs: ["Confirm root cause", "Confirm renewal/contract date", "Confirm save owner"],
    compliance_notes: [],
    evidence: ["Retention risk review (linked)", "Results trend (Vega)", "Payment context (Valerie)"],
    suggested_owner: "Vivian prepares · Nick/Jaxon own the save",
    notes: "Highest-stakes artifact in this lane; keep it evidence-based and human-led.",
  },
  {
    key: "upsell_opportunity_review",
    health_type: "upsell_opportunity_review",
    title: "Vault Co Upsell Opportunity Review",
    description: "Internal review of an expansion signal on a healthy client — what they could add and why now.",
    health_score: "{{score}}/100",
    risk_level_label: "Healthy",
    risk_reasons: [],
    missing_access: [],
    missing_assets: [],
    delivery_risks: ["Confirm delivery health supports expansion before any conversation"],
    communication_risks: [],
    next_best_actions: ["Validate the expansion hypothesis with results evidence first"],
    owner_notes: "Expansion only lands on top of proven results — verify before proposing internally.",
    save_plan: [],
    upsell_opportunities: ["{{opportunity}} — estimated value {{value}} (advisory)", "Why now: {{trigger}}"],
    missing_inputs: ["Confirm results evidence", "Confirm capacity to deliver the expansion"],
    compliance_notes: [],
    evidence: ["Results trend (Vega)", "Service usage pattern (Vivian)"],
    suggested_owner: "Vivian (Valerie sizes the revenue, advisory)",
    notes: "An internal hypothesis; any future proposal is human-led.",
  },
  {
    key: "monthly_client_health_closeout",
    health_type: "monthly_client_health_closeout",
    title: "Vault Co Monthly Client Health Closeout",
    description: "End-of-month internal closeout of a client's health: score movement, risks opened/closed, and the next period's focus.",
    health_score: "{{score}}/100 ({{delta}} vs last period)",
    risk_level_label: "{{risk_label}}",
    risk_reasons: ["Risks opened this period", "Risks closed this period"],
    missing_access: ["Carry-over access gaps, if any"],
    missing_assets: ["Carry-over asset gaps, if any"],
    delivery_risks: ["Delivery summary for the period"],
    communication_risks: ["Responsiveness summary for the period"],
    next_best_actions: ["Set the single focus item for next period"],
    owner_notes: "Roll the period's signals into one decision-ready read for Nick/Jaxon.",
    save_plan: [],
    upsell_opportunities: ["Expansion signals observed this period, if any"],
    missing_inputs: ["Confirm period", "Confirm revenue snapshot is reviewed"],
    compliance_notes: [],
    evidence: ["Revenue snapshot (period, internal aggregate)", "Health reviews from the period"],
    suggested_owner: "Vivian (Valerie supplies revenue context)",
    notes: "Pairs with the revenue closeout; uses internal aggregate values only.",
  },
  {
    key: "custom_health_draft",
    health_type: "custom",
    title: "Vault Co Custom Health Draft",
    description: "Blank, structured starting point for a bespoke Vault Co client-health artifact.",
    health_score: "{{score}}/100",
    risk_level_label: "{{risk_label}}",
    risk_reasons: ["Describe the signal that prompted this draft"],
    missing_access: [],
    missing_assets: [],
    delivery_risks: [],
    communication_risks: [],
    next_best_actions: ["Define the internal next step"],
    owner_notes: "Context for whoever picks this up.",
    save_plan: [],
    upsell_opportunities: [],
    missing_inputs: ["Score inputs", "Evidence"],
    compliance_notes: [],
    evidence: ["Add supporting evidence"],
    suggested_owner: "Vivian (Client Success Operator)",
    notes: "Use when none of the presets fit; fill in before review.",
  },
];

export function getClientHealthTemplate(key: string): ClientHealthTemplate | undefined {
  return CLIENT_HEALTH_TEMPLATES.find((t) => t.key === key);
}

export function clientHealthTemplateToInput(
  t: ClientHealthTemplate,
  opts: { client_id?: string | null; source_agent?: string | null } = {},
): VaultClientHealthDraftInput {
  return {
    client_id: opts.client_id ?? null,
    title: t.title,
    description: t.description,
    health_type: t.health_type,
    source_agent: opts.source_agent ?? "vivian",
    health_score: t.health_score,
    risk_level_label: t.risk_level_label,
    risk_reasons: t.risk_reasons,
    missing_access: t.missing_access,
    missing_assets: t.missing_assets,
    delivery_risks: t.delivery_risks,
    communication_risks: t.communication_risks,
    next_best_actions: t.next_best_actions,
    owner_notes: t.owner_notes,
    save_plan: t.save_plan,
    upsell_opportunities: t.upsell_opportunities,
    missing_inputs: t.missing_inputs,
    compliance_notes: t.compliance_notes,
    evidence: [`Template: ${t.title}`, `Suggested owner: ${t.suggested_owner}`, t.notes, ...t.evidence],
    metadata: { template_key: t.key, suggested_owner: t.suggested_owner },
  };
}
